services:
  - type: web
    name: hastakhar-api
    runtime: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
